spring:
  profiles:
    active: local
---
server:
  port: 8761  # Default : 8761
spring:
  profiles: local
  application:
    name: eurekaserver
  boot:
    admin:
      client:
        url:
        - http://localhost:8760
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  server:
    response-cache-update-interval-ms: 1000 # Eureka Server's Response Cache. Default 30,000ms
    enableSelfPreservation: false           # Just for demo
  client:
    register-with-eureka: false             # Only for local stand-alone development
    fetch-registry: false                   # Only for local stand-alone development
    service-url:
      defaultZone: http://localhost:8761/eureka  # Default Value. Just for demo
  instance:
    prefer-ip-address: true                 # Use ip address instead of hostname from OS when reporting myself to eureka server
    
logging:
  level:
    net.nalpari.eurekaserver: debug
    net.nalpari.eurekaserver.controller: debug
    net.nalpari.eurekaserver.service: debug
  file: D:/logs/eurekaserver-logging.log
---
server:
  port: 8761  # Default : 8761
spring:
  profiles: dev
  application:
    name: eurekaserver
  boot:
    admin:
      client:
        url:
        - http://10.150.80.42:8760
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  server:
    response-cache-update-interval-ms: 1000 # Eureka Server's Response Cache. Default 30,000ms
    enableSelfPreservation: false           # Just for demo
  client:
    register-with-eureka: false             # Only for local stand-alone development
    fetch-registry: false                   # Only for local stand-alone development
    service-url:
      defaultZone: http://10.150.80.42:8761/eureka  # Default Value. Just for demo
  instance:
    prefer-ip-address: true                 # Use ip address instead of hostname from OS when reporting myself to eureka server
    
logging:
  level:
    net.nalpari.eurekaserver: debug
    net.nalpari.eurekaserver.controller: debug
    net.nalpari.eurekaserver.service: debug
  file: /root/apps/logs/eurekaserver-logging.log